version: "3.3"
services:
  callisto:
    container_name: callisto
    image: yck1406/callisto:latest
    restart: unless-stopped
    env_file:
      - ./default.env
    volumes:
      - /volume1/docker/callisto/CHZZK-VOD:/home/callisto/CHZZK-VOD
